branches:
  only:
    - 0.4-candidate
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
install:
  - echo "TBD=$TRAVIS_BUILD_DIR"
  - ls $TRAVIS_BUILD_DIR/
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-setup-database.sh
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-install-domogik.sh
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - echo "Domogik installed!"
after_failure:
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-after-failure.sh
notifications:
  irc: "irc.freenode.net#domogik"

